services:
  worker:
    container_name: astrikos_worker
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    image: astrikos_worker
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/astrikos-worker/
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
