services:
  worker:
    container_name: astrikos_worker
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    image: astrikos_worker
    env_file: .env.setup
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
