FROM astrikos-environment-${id}:latest

WORKDIR /app

RUN pip install requests

RUN echo ${download_script} > ./download_script.py
RUN echo ${code} > ./main.py

RUN python download_script.py ${download_url}

RUN python main.py
